export const RowData = [
  {
    id: 1,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Approved',
    action: '...'
  },
  {
    id: 2,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Approved',
    action: '...'
  },
  {
    id: 3,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Pending',
    action: '...'
  },
  {
    id: 4,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Approved',
    action: '...'
  },
  {
    id: 5,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Approved',
    action: '...'
  },
  {
    id: 6,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Approved',
    action: '...'
  },
  {
    id: 7,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Pending',
    action: '...'
  },
  {
    id: 8,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Approved',
    action: '...'
  },
  {
    id: 9,
    bookingNo: 'B-5648498',
    customerName: 'Haris Awan',
    salon: 'Smart Cut',
    city: 'Jeddah',
    rating: '4.5',
    review: 'Lorem ipsum dolor sit amet consectetur. Pretium velit ornare pulvinar diam.',
    date: '18 Sep,2024',
    status: 'Approved',
    action: '...'
  },
]
