export const RowData = [
  {
    id: 1,
    salon: 'Smart Cut',
    serviceNumber: '08',
    location: 'Lake, California',
    distance: '2 KM',
    rating: 4.5,
  },
  {
    id: 2,
    salon: 'Smart Cut',
    serviceNumber: '08',
    location: 'Lake, California',
    distance: '2 KM',
    rating: 4.5,
  },
  {
    id: 3,
    salon: 'Smart Cut',
    serviceNumber: '08',
    location: 'Lake, California',
    distance: '2 KM',
    rating: 4.5,
  },
  {
    id: 4,
    salon: 'Smart Cut',
    serviceNumber: '08',
    location: 'Lake, California',
    distance: '2 KM',
    rating: 4.5,
  },
  {
    id: 5,
    salon: 'Smart Cut',
    serviceNumber: '08',
    location: 'Lake, California',
    distance: '2 KM',
    rating: 4.5,
  },
  {
    id: 6,
    salon: 'Smart Cut',
    serviceNumber: '08',
    location: 'Lake, California',
    distance: '2 KM',
    rating: 4.5,
  },
]
