export const RowData = [
  {
    id: 1,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'Pending',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  },
  {
    id: 2,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'Active',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  },
  {
    id: 3,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'Deleted',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  },
  {
    id: 4,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'Blocked',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  },
  {
    id: 5,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'Active',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  },
  {
    id: 6,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'Deleted',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  },
  {
    id: 7,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'InActive',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  },
  {
    id: 8,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'Active',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  },
  {
    id: 9,
    image: 'Image',
    salonName: 'Abs Salon',
    regdate: '09-12-2024',
    phoneNo: '+966-1234567',
    email: 'alex001@gmail.com',
    owner: 'Alex J Morison',
    status: 'Pending',
    city: 'Jeddah',
    category: 'Salon',
    action: '...'
  }
]
